// import type { NextPage } from 'next'
import Head from 'next/head';
import Translation from '../lib/Translation';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Snippet Creator</h1>
        <br />
        <Translation />
      </main>

      <footer className={styles.footer}>
        <a
          href='https://github.com/jameszhang-a/wordle-solver'
          target='_blank'
          rel='noopener noreferrer'
        >
          made by jz
        </a>
      </footer>
    </div>
  );
};

export default Home;
